name: qax
channels:
  - conda-forge
  - defaults
dependencies:
  - git
  - certifi
  - GDAL==3.6.2
  - tiledb==2.13.2
  - sphinx
  - qt-main==5.15.8
  - qt-webengine==5.15.8
  - qtawesome
  - cartopy
  - pyproj=3.4.1
  - pyside2==5.15.8
  - pywin32
  - numpy==1.23.5
  - scipy=1.10.0
  - numba==0.56.4
  - numexpr==2.8.3
  - pdal=2.5.0
  - python-pdal==3.2.2
  - rasterio==1.3.6
  - pip>=20.1
  - pip:
    - -r requirements.txt
