name: qax
channels:
  - conda-forge
  - defaults
dependencies:
  - git
  - certifi
  - GDAL==3.8.3
  - tiledb==2.19.1
  - sphinx==7.2.6
  - qt-main==5.15.8
  - qt-webengine==5.15.8
  - qtawesome==1.3.0
  - cartopy==0.22.0
  - proj==9.3.1
  - pyproj==3.6.1
  - pyside2==5.15.8
  - pywin32
  - numpy==1.26.4
  - scipy==1.12.0
  - numba==0.59.0
  - numexpr==2.9.0
  - conda-forge::pdal==2.6.3
  - conda-forge::python-pdal==3.3.0
  - rasterio>=1.3.9
  - pip==24.0
  - pip:
    - -r requirements.txt
