name: CI

on:
  push:
    branches:
      - "main"
      - "kk/*"
    tags:
      - "v.*"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  ci:
    uses: ausseabed/.github/.github/workflows/ci.yml@v1
    secrets:
        prefix_api_token: ${{ secrets.PREFIX_API_KEY }}