name: QAX Build

on:
  push:
    branches:
      - "main"
      - "kk/*"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  ci:
    uses: ausseabed/.github/.github/workflows/ci.yaml@main
    secrets:
        prefix_api_token: ${{ secrets.PREFIX_API_KEY }}