name: QAX Build

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'kk/*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - 'develop'
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest" 

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.9.5
        with:
          cache: true

      - name: Build Conda Package
        id: conda-package
        run: |
          pixi run mkconda
          echo "path=$(find . -name '*.conda' | head -1)" >> $GITHUB_OUTPUT

      - name: Upload conda package
        uses: actions/upload-artifact@v7
        with:
          path: ${{ steps.conda-package.outputs.path }}
          archive: false

  build-pdf:
    runs-on: "ubuntu-latest" 

    steps:
      - name: Setup LaTex
        run: |
          # texlive-core on conda is broken, and has been for some time apparently
          sudo apt-get update
          sudo apt-get install texlive-latex-extra latexmk texlive

      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.9.5
        with:
          cache: true

      - name: Build Docs (HTML)
        run: |
          pixi run mkdocs html

      - name: Build Docs (PDF)
        run: |
          pixi run mkdocs latexpdf

      - name: Upload QAX PDF Document
        uses: actions/upload-artifact@v7
        with:
          name: "HydrOfficeQAX.pdf"
          path: "docs/_build/latex/HydrOfficeQAX.pdf"
          retention-days: 6
